#!/bin/bash

# TODO: add config options for wp-config.php
# including: user, pw, db_name, host &
# define( 'JETPACK_DEV_DEBUG', true );

if [ $? != 0 ]
then
    exit 1
fi

vip=false

while getopts v flag; do
  case $flag in
    v) vip=true ; shift;;
    \?) echo "Invalid option: -$OPTARG" >&2 ; exit 1;;
  esac
done

svn co http://core.svn.wordpress.org/trunk/ $1

if [ vip ]
then
  echo "$1/wp-content/themes/vip/plugins"
  svn co https://vip-svn.wordpress.com/plugins/ "$1/wp-content/themes/vip/plugins"
fi